import = ["~/.config/alacritty/themes/mim.toml"]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 20, y = 20}

[font]
size = 11.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"
